<?php
/* 
 * Generated by Ravikumar Pulusu  
 * CRUDigniter v3.2
 */
 
class Businessideas extends CI_Controller{
    function __construct()
    {
	parent::__construct();
	$this->load->model('User_model');
	$this->load->model('Post_model');
	$this->load->library('session');
	$this->load->library('pagination');
	$session_user = $this->session->userdata('user'); 
	if($session_user){
			redirect('Ideazoneall');
		}
    }

    
	function index(){
		$data['bussinessIdeasall'] = $this->User_model->bussinessIdeasall();
		$config = array();
			$config["base_url"] = base_url() . "/businessideas/page";
			$total_row = count($data['bussinessIdeasall']);
			$config["total_rows"] = $total_row;
			$config["per_page"] = 10;
			$config['use_page_numbers'] = TRUE;
			$config['num_links'] = $total_row;
			$config['cur_tag_open'] = '&nbsp;<a class="btn btn-info">';
			$config['cur_tag_close'] = '</a>';
			$config['next_link'] = 'Next';
			$config['prev_link'] = 'Previous';

			$this->pagination->initialize($config);
			if($this->uri->segment(3)){
			$page = ($this->uri->segment(3)-1)*$config["per_page"];
			}
			else{
			$page = 0;
			}
			$data["bussinessIdeas"] = $this->User_model->getbussinessIdeasPage($config["per_page"], $page);
			$str_links = $this->pagination->create_links();
			$data["links"] = explode('&nbsp;',$str_links );
		
			$session_user = $this->session->userdata('user'); 
			
			$data['industry'] = $this->Post_model->getindustry();
			//$data['bussinessIdeas'] = $this->User_model->getbussinessIdeas();
			$data['user'] = $this->User_model->user_details($session_user);
			$this->load->view('user/business-ideas-user',$data);
	}
	function page(){
			$data['bussinessIdeasall'] = $this->User_model->bussinessIdeasall();	
		$config = array();
			$config["base_url"] = base_url() . "/businessideas/page";
			echo $total_row = count($data['bussinessIdeasall']); 
			$config["total_rows"] = $total_row;
			$config["per_page"] = 10;
			$config['use_page_numbers'] = TRUE;
			$config['num_links'] = $total_row;
			$config['cur_tag_open'] = '&nbsp;<a class="btn btn-info">';
			$config['cur_tag_close'] = '</a>';
			$config['next_link'] = 'Next';
			$config['prev_link'] = 'Previous';

			$this->pagination->initialize($config);
			if($this->uri->segment(3)){
			$page = ($this->uri->segment(3)-1)*$config["per_page"];
			}
			else{
			redirect('businessideas');
			}
			$data["bussinessIdeas"] = $this->User_model->getbussinessIdeasPage($config["per_page"], $page);
			$str_links = $this->pagination->create_links();
			$data["links"] = explode('&nbsp;',$str_links );
		
			$session_user = $this->session->userdata('user'); 
			
			$data['industry'] = $this->Post_model->getindustry();
			//$data['bussinessIdeas'] = $this->User_model->getbussinessIdeas();
			$data['user'] = $this->User_model->user_details($session_user);
			$data['page'] = $this->uri->segment(3);
			$this->load->view('user/business-ideas-user',$data);
	}
	function tag(){
		$session_user = $this->session->userdata('user'); 
			
		$tag = $this->uri->segment('2');  

		$query = $this->db->get_where('vh_tags', array('slug' => $tag));
		$tagsdata = $query->row_array();
		$tagid = $tagsdata['id'];

			$saved=1; 
			$data['tagname'] = $tagsdata['name'];
			$data['savedideas'] = $this->Post_model->idea_check_savedcount($session_user,$saved);
			$data['industry'] = $this->Post_model->getindustry();
			$data['bussinessIdeas'] = $this->User_model->getbussinessIdeasWithTag($tagid);
			$data['SavedIdeasb'] = $this->User_model->getbussinessIdeassaved($session_user);
			$data['PostedIdeas'] = $this->Post_model->getIdeasPosted($session_user);
			$data['InitiatedIdeas'] = $this->Post_model->getIdeasInitia($session_user);
			$data['InvestIdeas'] = $this->Post_model->getIdeasInvest($session_user);
			$data['locations'] = $this->Post_model->getlocation();	
			$data['user'] = $this->User_model->user_details($session_user);
			$data['skills_profiles'] = $this->Post_model->skills_profiles($session_user);
			$this->load->view('user/tags',$data);
    }
    
    function Industry($id){
	return $industry = $this->Post_model->getindustryby($id);
	}
    function Comments($id){
	return $comments = $this->Post_model->getComments($id);
	}
	function SubComments($id){
	return $comments = $this->Post_model->getSubComments($id);
	} 
	function Skill($id){
	 return $skill = $this->Post_model->getskilsbyid($id);
	}
	function userdata($id){
	 return $userdata = $this->User_model->user_details($id);
	}
	function comment_ById($id){
		$session_user = $this->session->userdata('user'); 	
	 return $chechLike=$this->Post_model->checkLikeComment($session_user,$id);	
	}
    function usersby($id){
	return $user = $this->User_model->user_details($id);
	}
	function FeedbackPost($id){
	return $feedback = $this->Post_model->Postfeedback_byId($id);
	//print_r($feedback);
	}
    function savedideacheck($ideaid,$uid){
	$saved=1; 
	
	return $savedideas = $this->Post_model->idea_check_saved($ideaid,$uid,$saved);
	}
    function investbyId($ideaid){
	$uid = $this->session->userdata('user'); 
	
	return $savedideas = $this->Post_model->idea_get_investedidea($ideaid,$uid);
	}
	function intiatedbyId($ideaid){
	$uid = $this->session->userdata('user'); 
	
	return $savedideas = $this->Post_model->idea_get_intiatedidea($ideaid,$uid);
	}
    
	
   


}
