<?php
/* 
 * Generated by CRUDigniter v3.2 
 * Ravipulusu
 */
 
class Gain extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Post_model');
    }

    function index()
    {
        $this->load->view('knowmore-gain');
    }
    function Entrepreneur(){
		
		$data['industry'] = $this->Post_model->getindustry();	
		$data['locations'] = $this->Post_model->getlocation();	
		$data['skils'] = $this->Post_model->getskils();	
		if(!empty($_POST)){
			
		$association = implode(",",$_POST['roles']);
 		$userid = $this->session->userdata('user'); 
		$userData = array(
                'industry' => strip_tags($this->input->post('industry')),
                'association' => strip_tags($association),
                'location' => strip_tags($this->input->post('location')),
                'currency' => strip_tags($this->input->post('currency')),
                'min_budget' => strip_tags($this->input->post('min_budget')),
                'max_budget' => strip_tags($this->input->post('max_budget')),
                'experience' => strip_tags($this->input->post('experience')),
                'nature' => strip_tags($this->input->post('nature')),
                'posted_by' => $userid,
                'post_type' => 'Entrepreneur',
            );
		$Insert = $this->Post_model->Insertgain($userData);
		if($Insert){
			$this->session->set_flashdata('msg','Your Entrepreneur Profile has been saved successfully. We appreciate your enthusiasm. We will come back to you with full version very soon.');
			redirect('Gain/Success');
		}else{
			$this->session->set_flashdata('msg','Failed Yours Entrepreneur');
			redirect('Gain/Success');
		}	
		
		}
		 $this->load->view('gain-entrepreneur',$data);
	}
	function Success(){
		$this->load->view('success-msg');
		
	}
	function Investor(){
		$data['industry'] = $this->Post_model->getindustry();	
		$data['locations'] = $this->Post_model->getlocation();	
		$data['skils'] = $this->Post_model->getskils();
		if(!empty($_POST)){
		//echo '<pre>'; print_r($_POST); echo '</pre>';	 exit;
		$association = implode(",",$_POST['roles']);
		$userid = $this->session->userdata('user'); 
		$userData = array(
                'industry' => strip_tags($this->input->post('industry')),
                'location' => strip_tags($this->input->post('location')),
				'association' => strip_tags($association),
                'investment_currency' => strip_tags($this->input->post('investment_currency')),
                'min_invest' => strip_tags($this->input->post('min_invest')),
                'max_invest' => strip_tags($this->input->post('max_invest')),
                'share_currency' => strip_tags($this->input->post('share_currency')),
                'min_share' => strip_tags($this->input->post('min_share')),
                'max_share' => strip_tags($this->input->post('max_share')),
				'posted_by' => $userid,
				'post_type' => 'Investor',
                
            );
		$Insert = $this->Post_model->Insertgain($userData);
		if($Insert){
			$this->session->set_flashdata('msg','Your Investor Profile has been saved successfully. We appreciate your enthusiasm. We will come back to you with full version very soon.');
			redirect('Gain/Success');
		}else{
			$this->session->set_flashdata('msg','Failed Yours Investor');
			redirect('Gain/Success');
		}	
		}
		$this->load->view('gain-investor',$data);
	}



}
