<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tag extends CI_Controller{
    function __construct()
    {
	parent::__construct();
	$this->load->model('User_model');
	$this->load->model('Post_model');
	$this->load->library('session');
    }

    
	function tag()
    {
		$session_user = $this->session->userdata('user'); 
			
		$tag = $this->uri->segment('2');  

		$query = $this->db->get_where('vh_tags', array('slug' => $tag));
		$tagsdata = $query->row_array();
		$tagid = $tagsdata['id'];

			$saved=1; 
			$data['tagname'] = $tagsdata['name'];
			$data['savedideas'] = $this->Post_model->idea_check_savedcount($session_user,$saved);
			$data['industry'] = $this->Post_model->getindustry();
			$data['bussinessIdeas'] = $this->User_model->getbussinessIdeasWithTag($tagid);
			$data['SavedIdeasb'] = $this->User_model->getbussinessIdeassaved($session_user);
			$data['PostedIdeas'] = $this->Post_model->getIdeasPosted($session_user);
			$data['InitiatedIdeas'] = $this->Post_model->getIdeasInitia($session_user);
			$data['InvestIdeas'] = $this->Post_model->getIdeasInvest($session_user);
			$data['locations'] = $this->Post_model->getlocation();	
			$data['user'] = $this->User_model->user_details($session_user);
			$data['skills_profiles'] = $this->Post_model->skills_profiles($session_user);
			$this->load->view('user/tags',$data);
    }
    
    function Industry($id){
	return $industry = $this->Post_model->getindustryby($id);
	}
    function Comments($id){
	return $comments = $this->Post_model->getComments($id);
	}
	function SubComments($id){
	return $comments = $this->Post_model->getSubComments($id);
	} 
	function Skill($id){
	 return $skill = $this->Post_model->getskilsbyid($id);
	}
	function userdata($id){
	 return $userdata = $this->User_model->user_details($id);
	}
	function comment_ById($id){
		$session_user = $this->session->userdata('user'); 	
	 return $chechLike=$this->Post_model->checkLikeComment($session_user,$id);	
	}
    function usersby($id){
	return $user = $this->User_model->user_details($id);
	}
	function FeedbackPost($id){
	return $feedback = $this->Post_model->Postfeedback_byId($id);
	//print_r($feedback);
	}
    function savedideacheck($ideaid,$uid){
	$saved=1; 
	
	return $savedideas = $this->Post_model->idea_check_saved($ideaid,$uid,$saved);
	}
    function investbyId($ideaid){
	$uid = $this->session->userdata('user'); 
	
	return $savedideas = $this->Post_model->idea_get_investedidea($ideaid,$uid);
	}
	function intiatedbyId($ideaid){
	$uid = $this->session->userdata('user'); 
	
	return $savedideas = $this->Post_model->idea_get_intiatedidea($ideaid,$uid);
	}
    
	
   


}
