<?php
/* 
 * Generated by Ravikumar pulusu 
 *
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Post_model');
        $this->load->model('User_model');
		$this->load->library('session');
		$session_user = $this->session->userdata('user'); 
				
    }
	function UploadImage(){
				$config['upload_path'] = 'uploads/images';
                $config['allowed_types'] = 'jpg|jpeg|png|gif';
                $config['file_name'] = time().$_FILES['avatar']['name'];
                
                $this->load->library('upload',$config);
                $this->upload->initialize($config);
                if($this->upload->do_upload('avatar')){
                    $uploadData = $this->upload->data();
                    $picture = $uploadData['file_name'];
                }else{
                   echo $picture = 'not upload'; exit; 
                }
				return $picture;

	}
	function Sendmailtest(){
		$phone ='pulusuravikumar@gmail.com';
		$otp_rndm='321123';
		$data = $this->Post_model->sendEmailotp($phone,$otp_rndm);
		echo $data;
	}
	function checksession(){
		
		echo $this->session->userdata('user'); 
		exit;
	}
	function SignUp(){
		if(!empty($_POST)){
		$phone= $this->input->post('phone');
		$email= $this->input->post('email');
		
		$phone_existnotauth = $this->User_model->phone_existnotauth($phone);
		$email_existau = $this->User_model->email_existnotauth($email);
		if(!empty($phone_existnotauth)){
			$this -> db -> where('MOBILENO', $phone);
			$this -> db -> delete('vh_usr');
		}
		$phone_exist = $this->User_model->phone_exist($phone);
		$email_exist = $this->User_model->email_exist($email);
		$name =$this->input->post('name');
		if(count($phone_exist)<=0){
			
		
		if(count($email_exist)<=0){
		$userData = array(
                'NAME' => strip_tags($this->input->post('name')),
                'MOBILENO' => strip_tags($this->input->post('phone')),
                'email' => strip_tags($this->input->post('email')),
                'PASSWORD' => md5($this->input->post('password')),
            );
		$update = $this->User_model->InsertUser($userData);
		if($update){
			$user_id = $update;
			$user_name = $name;
			$user_email = $email;
			$data['userid']=$update;
			$data['signup']=1;
			$data['email']=$user_email;
			$data['phone']=$phone;
			$data['uname']=$name;
			$data['uemail']=$email;
			
		}}else{
			$data['signup']=2;
		}}
		else{
			$data['signup']=3;
		}		
		echo json_encode($data); exit;
		}
		$this->load->view('user-signup');
	}
	function removeProfilepic(){
		$session_user = $this->session->userdata('user'); 
				$userData = array(
                'PROFILE_PICTURE' => ''
            );
		$update = $this->User_model->UpdateUser($userData,$session_user);
	if($update){
		echo "Done"; exit;
	}else{
		echo "Fail"; exit;		
	} 	
	}
	function Contact(){
		if(!empty($_POST)){
		$name= $this->input->post('name');
		$email= $this->input->post('email');
		$phone= $this->input->post('phone');
		$message= $this->input->post('message');
		$this->load->library('email');
		$this->email->set_newline("\r\n");
		$this->email->set_header('MIME-Version', '1.0; charset=utf-8'); 
		$this->email->set_header('Content-type', 'text/html'); 

		$this->email->from('ajay@viewham.com', 'Viewham');
		$this->email->to('ajayviewham@gmail.com');
		$this->email->reply_to($email);
		$this->email->subject('Viewham');

                $this->email->message('Welcome To Viewham. <br><br>  Name: '.$name.'
				<br> email: '.$email.'
				<br> phone: '.$phone.'
				<br> Message: '.$message.'
				');
               if($this->email->send()) {
				   echo 'Sent Succussful will get back to you Soon';
			   }else{
				  echo 'Sorry... not sent. Oops failed!'; 
			   }
		
		}
	}
	function Verifyemail($userid){
		$userDa = array(
                'EMAIL_AUTHENTICATED' => 1,
                'modefied_date' => date("Y-m-d H:i:s")
		);
		$auth_email = $this->User_model->Phone_update($userDa,$userid);
	if($auth_email){

	$this->session->set_flashdata('success', 'Email Succussful verified');
					redirect('User/Editprofile');
	}else{
	redirect('User/Editprofile');
	}	
	}
	function VerifyOtp(){
		if(!empty($_POST)){
		$phone= $this->input->post('phone');
		if(empty($phone)){
			$phone= $this->input->post('email');
		}
		$otp= $this->input->post('otp');
		$userid= $this->input->post('userid');
		$uemail= $this->input->post('uemail');
		$uname= $this->input->post('uname');
		$otpexist = $this->User_model->VerifyOtp($phone,$otp);
		
		if(count($otpexist)>0){
		$userData = array(
                'STATUS' => 1,
                'GENERATED_DATE' => date("Y-m-d H:i:s"),
            );
			$update = $this->User_model->UpdateOtpStatus($userData,$otpexist['ID']);
			
		if(is_numeric($phone))
		{
		$userDa = array(
                'MOB_AUTHENTICATED' => 1,
                'modefied_date' => date("Y-m-d H:i:s")
		);
		}else{
			$userDa = array(
                'EMAIL_AUTHENTICATED' => 1,
                'modefied_date' => date("Y-m-d H:i:s")
		);
		}
		$updatever = $this->User_model->Phone_update($userDa,$userid);
		if($updatever){
	$mailsend = $this->Post_model->sendEmailotp($uemail,$userid);		
	$this->session->set_userdata('user', $userid);
	$this->session->set_userdata('username', $uname);
	$this->session->set_userdata('useremail', $uemail);
	$session_user = $this->session->userdata('user');
			echo '1'; exit;
		}else{
			echo "2"; exit;
		}	

		}else{
			echo "3";exit;
		}
		}
	}
	function VerifyOtpForgot(){
		if(!empty($_POST)){
		$phone= $this->input->post('phone');
		if(empty($phone)){
			$phone= $this->input->post('email');
		}
		$otp= $this->input->post('otp');
		$userid= $this->input->post('userid');
		$uemail= $this->input->post('uemail');
		$uname= $this->input->post('uname');
		$otpexist = $this->User_model->VerifyOtp($phone,$otp);
		if(count($otpexist)>0){
		$userData = array(
                'STATUS' => 1,
                'GENERATED_DATE' => date("Y-m-d H:i:s"),
            );
			$update = $this->User_model->UpdateOtpStatus($userData,$otpexist['ID']);
			
		
		if($update){
	
			echo '1'; exit;
		}else{
			echo "2"; exit;
		}	

		}else{
			echo "3";exit;
		}
		}
	}
	function UpdatePassword(){
		if(!empty($_POST)){
		$password= $this->input->post('password');
		$phone= $this->input->post('phone');
		$userData = array(
                'PASSWORD' => md5($password),
                'modefied_date' => date("Y-m-d H:i:s")
            );
			$update = $this->User_model->UpdatePassword($userData,$phone);
			
		if($update){
			echo '1'; exit;
		}else{
			echo "2"; exit;
		}	

		}
	}
	function SendOtp(){
		if(!empty($_POST)){
		$phone= $this->input->post('phone');
		$email= $this->input->post('email');
		if(!empty($phone)){
		$phone_exist = $this->User_model->phone_exist($phone);
		$vl=$phone;
		}elseif(!empty($email)){
		$phone_exist = $this->User_model->email_exist($email);
		$vl=$email;
		}
		
		if(count($phone_exist)>0){
			
		$otp_rndm = mt_rand(100000, 999999);
		if (is_numeric($phone))
		{
			$msg='Viewham Forget password OTP is '.$otp_rndm;
			$data = $this->Post_model->sendsmsotp($phone,$msg);
			} else {
			$data = $this->Post_model->sendEmailotp($phone,$otp_rndm);
			}
		
		$userData = array(
                'PHONE' => $vl,
                'OTP' => $otp_rndm,
                'STATUS' => 0,
                'GENERATED_DATE' => date("Y-m-d H:i:s"),
            );

		$insert = $this->User_model->InsertOtp($userData);
		if($insert){
			echo '1'; exit;
		}else{
			echo "2"; exit;
		}	

		}else{
			echo "Enter Valid Phone Number"; exit;
		}
		}
	}
	function AjaxSignUp(){
		if(!empty($_POST)){
				$userData = array(
                'NAME' => strip_tags($this->input->post('uname')),
                'MOBILENO' => strip_tags($this->input->post('rmobile')),
                'EMAIL' => strip_tags($this->input->post('remail')),
                'PASSWORD' => md5($this->input->post('rpwd')),
            );
		$insert = $this->User_model->InsertUser($userData);
		if($insert){
			echo $insert; exit;
		}else{
			echo "failed Create"; exit;
		}	

		}
		$this->load->view('user-signup');
	}
	function index(){
		$this->load->view('user-signup');
	}
	function AjaxSignIn(){
	if(!empty($_POST)){
	
	$usn = $this->input->post('uid');
	$pwd = $this->input->post('pwd');
	$query = $this->User_model->user_login($usn,$pwd);

	
  
	if($query){
	$user_id = $query['ID'];
	$user_name = $query['NAME'];
	$user_email = $query['EMAIL'];
	
	$this->session->set_userdata('user', $user_id);
	$this->session->set_userdata('username', $user_name);
	$this->session->set_userdata('useremail', $user_email);	
	echo $user_id = $query['ID']; exit;
	
	
	}else{
	echo "Enter valid login Credentials"; exit;
	}
	}
        $this->load->view('user-signin');
    }
	function SignIn(){
	if($this->session->userdata('user')){
		redirect('User/Dashboard');	
	}
	if(!empty($_POST)){
	$usn = $this->input->post('email');
	$pwd = $this->input->post('password');
	$query = $this->User_model->user_login($usn,$pwd);
 
	if($query){
	$user_id = $query['ID'];
	$user_name = $query['NAME'];
	$user_email = $query['EMAIL'];
	
	$this->session->set_userdata('user', $user_id);
	$this->session->set_userdata('username', $user_name);
	$this->session->set_userdata('useremail', $user_email);
	$session_user = $this->session->userdata('user');
		redirect('ideazone-all');
	}else{
		$this->session->set_flashdata('error','Please Enter Valid Credentials'); 
		redirect('User/SignIn');
	}
	}
        $this->load->view('user-signin');
    }
	function Dashboard(){
		 $session_user = $this->session->userdata('user'); 
		if(empty($session_user)){
			redirect('User/SignIn');
		}
		$data['user'] = $this->User_model->user_details($session_user);

		$this->load->view('admin/user-dashboard',$data);
	}
	function Editprofile(){
		$session_user = $this->session->userdata('user'); 
		if(!empty($_POST)){

	 if(!empty($_FILES['avatar']['name'])){
				$picture = $this->UploadImage();
						}else{
				$picture =$this->input->post('imageprofile');		
						}
		$userData = array(
                'NAME' => strip_tags($this->input->post('name')),
                'MOBILENO' => strip_tags($this->input->post('mobile')),
                'EMAIL' => strip_tags($this->input->post('email')),
                'PROFILE_PICTURE' =>  $picture,
                'LINKEDIN_ID' =>  strip_tags($this->input->post('Linkedin')),
                'GENDER' =>  strip_tags($this->input->post('GENDER')),
                'DOB' =>  strip_tags($this->input->post('age')),
               
            );
		 $Updates = $this->User_model->UpdateUser($userData,$session_user);
		if($Updates){
				$this->session->set_flashdata('success', 'This is my message');
				redirect('User/Editprofile');
			}else{
				echo "Update failed "; exit;
			}
	}
		$data['user'] = $this->User_model->user_details($session_user);
		$this->load->view('admin/user-editprofile',$data);
	}
	function Quicklinks(){
		$session_user = $this->session->userdata('user'); 
		$data['user'] = $this->User_model->user_details($session_user);
		$this->load->view('admin/user-quick-links',$data);
	}
	function logout(){
      $user_data = $this->session->all_userdata();

    $this->session->sess_destroy();
    redirect('');
    }
	function SendOtpRegister(){
		if(!empty($_POST)){
		$userid = $this->session->userdata('user');	
		$phone= $this->input->post('phone');
		$email= $this->input->post('email');
		if(!empty($phone)){
			$userData = array(
                'MOBILENO' => $phone,
                'modefied_date' => date("Y-m-d H:i:s"),
            );
		//$phone_exist = $this->User_model->Phone_update($userData,$userid);
		$vl=$phone;
		}elseif(!empty($email)){
		$userData = array(
                'EMAIL' => $email,
                'modefied_date' => date("Y-m-d H:i:s"),
            );	
		//$phone_exist = $this->User_model->Email_update($userData,$userid);
		$vl=$email;
		}
		
			
		$otp_rndm = mt_rand(100000, 999999);
		if (is_numeric($phone))
		{	
			$msg='Welcome to Viewham Business Ideas. OTP : '.$otp_rndm;
			$data = $this->Post_model->sendsmsotp($phone,$msg);
			} else {
			$data = $this->Post_model->sendEmailotp($phone,$otp_rndm);
			}
		
		$userData = array(
                'PHONE' => $vl,
                'OTP' => $otp_rndm,
                'STATUS' => 0,
                'GENERATED_DATE' => date("Y-m-d H:i:s"),
            );

		$insert = $this->User_model->InsertOtp($userData);
		if($insert){
			echo '1'; exit;
		}else{
			echo "2"; exit;
		}	

		
		}
	}
	
	function MobileSendOtp(){
		if(!empty($_POST)){
		$userid = $this->session->userdata('user');	
		$phone= $this->input->post('phone');
		$email= $this->input->post('email');
		if(!empty($phone)){
			$userData = array(
                'MOBILENO' => $phone,
                'modefied_date' => date("Y-m-d H:i:s"),
            );
		$phone_exist = $this->User_model->Phone_update($userData,$userid);
		$vl=$phone;
		}elseif(!empty($email)){
		$userData = array(
                'EMAIL' => $email,
                'modefied_date' => date("Y-m-d H:i:s"),
            );	
		$phone_exist = $this->User_model->Email_update($userData,$userid);
		$vl=$email;
		}
		if(count($phone_exist)>0){
			
		$otp_rndm = mt_rand(100000, 999999);
		if (is_string($phone))
		{
			//$data = $this->Post_model->sendsmsotp($phone,$otp_rndm);
			} else {
			//$data = $this->Post_model->sendEmailotp($phone,$otp_rndm);
			}
		
		$userData = array(
                'PHONE' => $vl,
                'OTP' => $otp_rndm,
                'STATUS' => 0,
                'GENERATED_DATE' => date("Y-m-d H:i:s"),
            );

		$insert = $this->User_model->InsertOtp($userData);
		if($insert){
			echo '1'; exit;
		}else{
			echo "2"; exit;
		}	

		}else{
			echo "Enter Valid Phone Number";
		}
		}
	}
	public function SendOpt() {
	 $phone="9505191822";
	 $otpn="test one";
	 
		 $data = $this->Post_model->sendsmsotp($phone,$otpn);
		 echo $data; exit;
 }
	}